### ISSUE TITLE
`latest` tag not kept updated

### ISSUE THREAD

**Issue by Sacro** [adevinta/noe#107]
The helm chart values uses `latest` as the image version, but it looks like that's not kept updated with the CI builds.

**Comment by tjamet** [comment]
Hi!
Thanks for raising.
Indeed, there is a mistake in the github actions workflow.
This should be fized by #118

**Comment by tjamet** [comment]
With the fix, the latest tag is correctly updated, as you can see [here](https://github.com/adevinta/noe/pkgs/container/noe/221820952?tag=latest)
I will hence close this ticket. Feel free to re-open if you find further complications
