### ISSUE TITLE
"/vendor": not found on docker build 

### ISSUE THREAD

**Issue by pchar** [adevinta/noe#59]
Hi,

im looking to your project I'm interested in. 
I'checkout the source code and simply run 
docker build .   (because your repository ghcr.io/adevinta/noe:latest in not public )

throws this error 

```
 => ERROR [builder 5/8] COPY vendor/ vendor/                                                                                                                                                   0.0s
------
 > [builder 5/8] COPY vendor/ vendor/:
------
Dockerfile:9
--------------------
   7 |     COPY go.mod go.mod
   8 |     COPY go.sum go.sum
   9 | >>> COPY vendor/ vendor/
  10 |     
  11 |     # Copy the go source
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 23afac0f-5bd1-4d31-b003-60d06acc2970::mlxrgq9q2tz3cblysydpiyis2: "/vendor": not found

```

**Comment by tjamet** [comment]
Hi!

This repo requires to run `go mod vendor` prior to running `docker build .`, as in the build github actions https://github.com/adevinta/noe/blob/00ec399d46d9dfa53f0ebec1c09501d98a4ae2f2/.github/workflows/build.yaml#L32

Happy to see a PR to improve this behaviour

**Comment by tjamet** [comment]
Copying of vendor has been removed in #119 
Closing this issue
